# Wisconsin Breast Cancer
## Binary classification problem which records clinical measurements of breast cancer tumors.
### Import required libraries

In [24]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

from sklearn.neighbors import KNeighborsRegressor

### Load Dataset and Analyse it

In [3]:
cancer_data = load_breast_cancer()
cancer_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

#### Information of Cancer Data 

In [5]:
data = pd.DataFrame(cancer_data.data, columns = cancer_data.feature_names)
data.head()

mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0        17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1        20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2        19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3        11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4        20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678

[5 rows x 30 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

#### Decribe the Cancer Data

In [7]:
data.describe()

mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
count   569.000000    569.000000      569.000000  ...            569.000000      569.000000               569.000000
mean     14.127292     19.289649       91.969033  ...              0.114606        0.290076                 0.083946
std       3.524049      4.301036       24.298981  ...              0.065732        0.061867                 0.018061
min       6.981000      9.710000       43.790000  ...              0.000000        0.156500                 0.055040
25%      11.700000     16.170000       75.170000  ...              0.064930        0.250400                 0.071460
50%      13.370000     18.840000       86.240000  ...              0.099930        0.282200                 0.080040
75%      15.780000     21.800000      104.100000  ...              0.161400        0.317900                 0.092080
max      28.110000     39.280000      188.500000  ...              0.291000        0.663800                 0.207500

[8 rows x 30 columns]

#### Shape of Cancer Data

In [8]:
data.shape

(569, 30)

#### Target Names in Cancer Data

In [14]:
cancer_data.target_names

array(['malignant', 'benign'], dtype='<U9')

#### Feature Names in Cancer Data

In [15]:
cancer_data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

#### Sample count of each class in Cancer Data

In [23]:
for n, v in zip(cancer_data.target_names , np.bincount(cancer_data.target)):
    print(f'{n}: {v}')

malignant: 212
benign: 357


### Training & Testing of Breast Cancer Data
#### 1- Split the data into X & y 

In [81]:
X_train, X_test, y_train, y_test = train_test_split(
    cancer_data.data,
    cancer_data.target,
    random_state = 50,
    test_size = 30,
    stratify= cancer_data.target
)

##### X_train

In [82]:
X_train

array([[1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [1.791e+01, 2.102e+01, 1.244e+02, ..., 1.964e-01, 3.245e-01,
        1.198e-01],
       [1.420e+01, 2.053e+01, 9.241e+01, ..., 1.339e-01, 2.534e-01,
        7.858e-02],
       ...,
       [1.131e+01, 1.904e+01, 7.180e+01, ..., 6.961e-02, 2.400e-01,
        6.641e-02],
       [1.175e+01, 1.756e+01, 7.589e+01, ..., 1.010e-01, 2.478e-01,
        7.757e-02],
       [1.328e+01, 2.028e+01, 8.732e+01, ..., 1.492e-01, 3.739e-01,
        1.027e-01]], shape=(539, 30))

##### y_train

In [83]:
y_train

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,

##### X_test

In [84]:
X_test

array([[9.333e+00, 2.194e+01, 5.901e+01, 2.640e+02, 9.240e-02, 5.605e-02,
        3.996e-02, 1.282e-02, 1.692e-01, 6.576e-02, 3.013e-01, 1.879e+00,
        2.121e+00, 1.786e+01, 1.094e-02, 1.834e-02, 3.996e-02, 1.282e-02,
        3.759e-02, 4.623e-03, 9.845e+00, 2.505e+01, 6.286e+01, 2.958e+02,
        1.103e-01, 8.298e-02, 7.993e-02, 2.564e-02, 2.435e-01, 7.393e-02],
       [1.287e+01, 1.621e+01, 8.238e+01, 5.122e+02, 9.425e-02, 6.219e-02,
        3.900e-02, 1.615e-02, 2.010e-01, 5.769e-02, 2.345e-01, 1.219e+00,
        1.546e+00, 1.824e+01, 5.518e-03, 2.178e-02, 2.589e-02, 6.330e-03,
        2.593e-02, 2.157e-03, 1.390e+01, 2.364e+01, 8.927e+01, 5.975e+02,
        1.256e-01, 1.808e-01, 1.992e-01, 5.780e-02, 3.604e-01, 7.062e-02],
       [1.371e+01, 1.868e+01, 8.873e+01, 5.710e+02, 9.916e-02, 1.070e-01,
        5.385e-02, 3.783e-02, 1.714e-01, 6.843e-02, 3.191e-01, 1.249e+00,
        2.284e+00, 2.645e+01, 6.739e-03, 2.251e-02, 2.086e-02, 1.352e-02,
        1.870e-02, 3.747e-03, 1.511e

##### y_test

In [85]:
y_test

array([1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0])

#### 2- Train the model through KNN

In [86]:
knn = KNeighborsClassifier(n_neighbors=7)

In [87]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

#### 3- Predict the model on Test Data

In [88]:
y_pred = knn.predict(X_test)

In [89]:
print(y_pred)

[1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0]


#### 4- Evaluate that model through metrics

In [90]:
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc}")

Accuracy: 0.9666666666666667
